# Site settings
title: "K.Q. Dreger"
email: "comments@dreger.me"
description: "Liberal arts, in your browser."
url: "http://web.kqdreger.com" 
timezone: '-0600'
icon: '&#9650;'
permalink: /:title

# Build settings
sass:
  style: compressed
markdown: kramdown 
highlighter: rouge
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: "_posts/writing"
    values:
      category: writings
      layout: "post"
      hidden: true
  -
    scope:
      path: "_posts/snippets"
    values:
      category: snippets
      layout: "snippet"
      permalink: /snippets/:short_year:month:day:hour:minute:second
  -
    scope:
      path: "_posts/hidden"
    values:
      category: hidden
