# standard jekyll configuration
source:         ./_src
destination:    ./_site
pygments:       true
markdown:       rdiscount
rdiscount:
  extensions: [footnotes]
  # extensions: [ footnotes ]

# gems: [permalinkrewriter]
# paginate: 1
# timezone:       nil
# future:         true
# show_drafts:    false
pygments:       true

# required configuration
domain:         http://kyledreger.com
title:          Kyle Dreger
author:         Kyle Dreger
email:          dregerkq@mountunion.edu
description:    "Well-written Nerdery"

# typekit:
#   id:           eqd7pqa
# google_analytics:
#   account:      UA-17208416-21
