auto: true
permalink: /:title
server_port: 5000
pygments: true

# Setup
author: Kyle Dreger
email: hi@kyledreger.com
title: Less of me
description: "Kyle is a programmer, writer and designer. A triple threat. Maybe."
analytics: UA-17208416-14
domain: kyledreger.com