# standard jekyll configuration
# source: ./_src
# destination: ./_site
permalink: /posts/:title
pygments: true
auto: true
markdown: rdiscount

# required configuration
domain: dreger.co
title: Kyle Dreger
author: Kyle Dreger
email: me@kyledreger.com
description: "Jesus is life. Simplicity is freedom. Rise."

typekit:
  id: eqd7pqa
google_analytics:
  account: UA-17208416-19
