url: http://kyledreger.com
domain: http://kyledreger.com
title: "Kyle Dreger"
name: "Kyle Dreger"
author: Kyle Dreger
email: comments@dreger.me
description: "A column about design and writing."
markdown: rdiscount
highlighter: pygments
permalink: /:categories/:year/:month/:day/:title.html
permalink: /archives/:short_year:y_day-:title.html
timezone: "America/New_York"

rdiscount:
  extensions: [footnotes, smart]

gems:
  - jekyll-sitemap
  - jekyll-feed

sass:
    style: :compressed

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: "linked"
      type: posts
    values:
      layout: post
      category: "linked"
  -
    scope:
      path: "article"
      type: posts
    values:
      layout: post