url: http://kyledreger.com
domain: http://kyledreger.com
title: kyledreger.com
author: Kyle Dreger
email: comments@dreger.me
description: "Something audacious."
markdown: rdiscount
highlighter: pygments
permalink: /posts/:title.html
timezone: "America/New_York"

rdiscount:
  extensions: [footnotes, smart]

gems:
  - jekyll-sitemap

sass:
  style: compressed
  deploy_style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink:
  -
    scope:
      path: "best-of"
      type: "posts"
    values:
      category: bestof
