
url:            http://kyledreger.com
domain:         http://kyledreger.com
title:          Kyle Dreger
author:         Kyle Dreger
email:          comments@dreger.me
description:    "Well-written Nerdery"
permalink: /archives/:title.html
source:         ./_src
destination:    ./_site
markdown:       rdiscount
highlighter:       pygments

rdiscount:
  extensions: [footnotes, smart]

sass:
  style:  compressed
  deploy_style: compressed
