# Site settings
title: "K.Q. Dreger"
author: "K.Q. Dreger"
twitter: "@Dreger"
email: "comments@dreger.me"
description: "Liberal arts, in your browser."
url: "http://web.kqdreger.com" 
timezone: '-0600'
icon: '&#9650;'
permalink: /:year/:month/:title.html

# Build settings
sass:
  style: compressed
markdown: kramdown 
highlighter: rouge
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: "_posts/published"
    values:
      category: published
      layout: "post"
  -
    scope:
      path: "_posts/hidden"
    values:
      hidden: true
