# required configuration
url:            http://kyledreger.com
domain:         http://kyledreger.com
title:          Kyle Dreger
author:         Kyle Dreger
email:          comments@dreger.me
description:    "Well-written Nerdery"

# standard jekyll configuration
source:         ./_src
destination:    ./_site
markdown:       rdiscount
rdiscount:
  extensions: [footnotes, smart]
permalink: /archives/:title.html
highlighter:       pygments
sass:
    style:  compressed  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
