url: http://kyledreger.com
domain: http://kyledreger.com
title: "Kyle Dreger"
author: Kyle Dreger
email: comments@dreger.me
description: "Something audacious."
markdown: rdiscount
highlighter: pygments
permalink: /:title.html
permalink: /archives/:short_year:y_day-:title.html
timezone: "America/New_York"

rdiscount:
  extensions: [footnotes, smart]

gems:
  - jekyll-sitemap

sass:
  style: compressed
  deploy_style: compressed

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: "published"
      type: posts
    values:
      layout: post
      category: "published"
  -
    scope:
      path: "ideas"
      type: posts
    values:
      layout: post
      category: "ideas"
