# standard jekyll configuration
source:         ./_src
destination:    ./_site
permalink:      /blog/:year/:month/:title.html
pygments:       true
markdown:       rdiscount
# paginate: 1
# timezone:       nil

# future:         true
# show_drafts:    false
# limit_posts:    0
pygments:       true

# required configuration
domain:         http://kyledreger.com
title:          Kyle Dreger
author:         Kyle Dreger
email:          comments@kyledreger.com
description:    "Well-written Nerdery"

# typekit:
#   id:           eqd7pqa
# google_analytics:
#   account:      UA-17208416-21

