# standard jekyll configuration
source:         ./_src
destination:    ./_site
permalink:      /:year/:month/:title
pygments:       true
markdown:       rdiscount
# paginate: 1
# timezone:       nil

# future:         true
# show_drafts:    false
# limit_posts:    0
pygments:       true

# required configuration
domain:         kyledreger.com
title:          Kyle Dreger
author:         Kyle Dreger
email:          desk@kyledreger.com
description:    "Jesus is life. Simplicity is freedom. Rise."

typekit:
  id:           eqd7pqa
# google_analytics:
#   account:      UA-17208416-19
