url: http://kyledreger.com
domain: http://kyledreger.com
title: "K.Q. Dreger"
author: K.Q. Dreger
email: comments@dreger.me
description: "Something audacious."
markdown: rdiscount
highlighter: pygments
permalink: /:title.html
permalink: /archives/:short_year:y_day-:title.html
timezone: "America/New_York"

rdiscount:
  extensions: [footnotes, smart]

gems:
  - jekyll-sitemap

sass:
  style: compressed
  deploy_style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /archives/:short_year:y_day-:title.html
  -
    scope:
      path: "essays"
      type: "posts"
    values:
      category: essays
      permalink: /:title.html
  -
    scope:
      path: "notes"
      type: "posts"
    values:
      category: notes
      permalink: /:title.html
