# Site settings
title: "K.Q. Dreger"
author: "K.Q. Dreger"
twitter: "@Dreger"
email: "comments@dreger.me"
description: "Liberal arts, in your browser."
url: "https://dreger.me" 
timezone: '-0600'
icon: '&#9650;'
permalink: /writing/:title

# Build settings
sass:
  style: compressed
markdown: kramdown 
highlighter: rouge
excerpt_separator: "<!-- more -->"
destination: _kqd

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: "_posts/published"
    values:
      layout: "post"
      category: published
  -
    scope:
      path: "_posts/hidden"
    values:
      hidden: true
      layout: "post"
