url: http://audaciousfox.com
domain: http://audaciousfox.com
title: Audacious Fox
author: Kyle Dreger
email: comments@audaciousfox.com
description: "Something audacious."
source: ./_src
destination: ./_site
markdown: rdiscount
highlighter: pygments
timezone: "America/New_York"

rdiscount:
  extensions: [footnotes, smart]

sass:
  style: compressed
  deploy_style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
