# Site settings
title: "K.Q. Dreger"
author: "K.Q. Dreger"
twitter: "@Dreger"
email: "comments@dreger.me"
description: "Director of product by day, writer by night, baker by nighter night."
url: "https://dreger.me" 
permalink: /:title

# Build settings
sass:
  style: compressed
markdown: kramdown 
highlighter: rouge
excerpt_separator: "<!-- more -->"
destination: _public

defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
      permalink: /blog/:title