# standard jekyll configuration
source:         ./_src
destination:    ./_site
markdown:       rdiscount
rdiscount:
  extensions: [footnotes, smart]
  # extensions: [ footnotes ]

# gems: [permalinkrewriter, sitemap_generator]
# paginate: 1
# timezone:       nil
# future:         true
# show_drafts:    false
highlighter:       pygments

# required configuration
url:            http://kyledreger.com
domain:         http://kyledreger.com
title:          Kyle Dreger
author:         Kyle Dreger
email:          dregerkq@mountunion.edu
description:    "Well-written Nerdery"

# typekit:
#   id:           eqd7pqa
# google_analytics:
#   account:      UA-17208416-21
defaults:
  -
    scope:
        path: "" # empty string for all files
    values:
        layout: "defualt"
