# standard jekyll configuration
source:         ./_src
destination:    ./_site
markdown:       rdiscount
rdiscount:
  extensions: [footnotes, smart]

permalink: /:title.html


highlighter:       pygments

# required configuration
url:            http://kyledreger.com
domain:         http://kyledreger.com
title:          Kyle Dreger
author:         Kyle Dreger
email:          dregerkq@mountunion.edu
description:    "Well-written Nerdery"

sass:
    style:  compressed  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    # "deploy_style:" is used only for building the site
    # (ie: not using the --watch flag)
#
#
# name: "Kyle Q. Dreger, Writer and Designer"
# description: Designer
# # url: https://dreger.me
#
# gems:
# - jekyll-sitemap
#
# markdown: kramdown
#
# highlighter: true
#
# permalink: pretty
#
# include: [".htaccess"]
# exclude: ["node_modules", "package.json", "Gruntfile.js"]
#
# asset_bundler:
#   markup_templates:
#     js: "<script type='text/javascript' src='{{url}}' async></script>\n"
#     css: "<link rel='stylesheet' type='text/css' href='{{url}}' />\n"
#   compress: yui
