# standard jekyll configuration

permalink: /:title
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount

# configuration required for some pages

domain: blog.kyledreger.com
title: Kyle Dreger
author: Kyle Dreger
email: me@kyledreger.com
description: "Jesus is life. Simplicity is freedom. Rise."

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

google_analytics:
  account: UA-17208416-19

github:
  username: dreger

# disqus:
#   id: disqusid
