auto: true
permalink: /:title
server_port: 5000

# Setup
author: Kyle Dreger
twitter: dreger
email: hi@kyledreger.com
title: Spark
description: "Never stop building."
analytics: UA-17208416-14
domain: kyledreger.com