baseURL = "https://dreger.me/"
languageCode = "en-us"
title = "K.Q. Dreger"
uglyurls = false
publishDir = "docs"
disableKinds = ["RSS", "taxonomy", "section"]
ignoreErrors = ["error-disable-taxonomy"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
	notes = "/:filename"
	pages = "/:filename"
